#!/bin/bash
#$ -N frontish
#$ -P cs599dg
#$ -l h_rt=02:00:00
#$ -pe omp 4
#$ -l h_vmem=8G
#$ -j y
#$ -o batchJob/logs/log_frontish.txt
#$ -cwd

# ---- LIMIT THREADS TO 4 CORES ----
export OMP_NUM_THREADS=4
export OPENBLAS_NUM_THREADS=4
export MKL_NUM_THREADS=4
export NUMEXPR_NUM_THREADS=4
export VECLIB_MAXIMUM_THREADS=4
export OPENCV_NUM_THREADS=4

source venv/bin/activate

python -u script/data_processing/get_frontish_faces.py