#!/bin/bash
#$ -N ff_val_norm_cpu
#$ -P cs599dg
#$ -l h_rt=06:00:00
#$ -l h_vmem=8G
#$ -pe omp 4
#$ -cwd
#$ -j y
#$ -o batchJob/logs/log_ff_val_norm_cpu.txt

echo "Host: $(hostname)"

export OMP_NUM_THREADS=4
export OPENBLAS_NUM_THREADS=4
export MKL_NUM_THREADS=4
export NUMEXPR_NUM_THREADS=4
export VECLIB_MAXIMUM_THREADS=4

source venv/bin/activate

python -u script/eval/run_fairface.py \
  --data_root data/cleaned/frontish \
  --split validation \
  --use_norm